In [4]:
import os
import cv2
import random
import numpy as np
import sys

# -----------------------------------------------------------------
# -----------------------------------------------------------------
image_name='13'
image_extension='.jpg'
image_path='d:/Path/rec/image/{}'.format(image_name+image_extension)
save_path='d:/Path/rec/annot/'
cluster_name='cutter'
idd=image_name

# -----------------------------------------------------------------
# -----------------------------------------------------------------

xmin=[]
ymin=[]
xmax=[]
ymax=[]
drawing=False
def click_event(event,x,y,flags,params):
    global ix,iy,drawing,xx,yy
    if event==cv2.EVENT_LBUTTONDOWN:
        drawing = True
        print('x min : {}  |  y min :{} '.format(x,y))
        xmin.append(x)
        ymin.append(y)
        ix,iy = x,y
        cv2.imshow('image', img)
            
    elif event==cv2.EVENT_LBUTTONUP:
        drawing=False
        print('x max : {}  |  y max :{} '.format(x,y))    
        xmax.append(x)
        ymax.append(y)
        c1,c2,c3=random.randint(0,255),random.randint(0,255),random.randint(0,200)
        cv2.rectangle(img,(ix,iy),(x,y),(c1,c2,c3),thickness=2)
        cv2.imshow('image', img)
    
#
if __name__=='__main__':
    img=cv2.imread(image_path)                        #   Image PATH
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey(0)
    cv2.destroyAllWindows() 
    


xy=np.array([xmin,ymin,xmax,ymax])
print(xy.shape)
print(xy)

src_img=cv2.imread(image_path)                        #   Image PATH
w,h,c=src_img.shape

from xml.dom import minidom, Node


root=minidom.Document()

def kind(object_name,roott,inside):
    '''
    obj_name is the objact to create 
    root : where to obj_name connect to
    inside is the text inside the obj_name
    '''
    obj=root.createElement(str(object_name))
    if inside:
        obj.appendChild(root.createTextNode(inside))
    roott.appendChild(obj)
    return obj


unn       =kind('annotion',root,None)
folder    =kind('path',unn,image_path)
file_n    =kind('filename',unn,'{}'.format(idd))
pic_size  =kind('size',unn,None)
pic_width =kind('width',pic_size,'{}'.format(h))
pic_height=kind('height',pic_size,'{}'.format(w))
dep       =kind('depth',pic_size,'{}'.format(c))
seg       =kind('segmented',unn,'0')
for i in np.arange(0,len(xmin)):
        obj       =kind('object',unn,None)
        name      =kind('name',obj,cluster_name)
        pos       =kind('pos',obj,'Unspecified')
        truncated =kind('truncated',obj,'0')
        difficult =kind('difficult',obj,'0')
        bndbox    =kind('bndbox',obj,None)
        xmi       =kind('xmin',bndbox,str(xmin[i]))
        ymi       =kind('ymin',bndbox,str(ymin[i]))
        xma       =kind('xmax',bndbox,str(xmax[i]))
        yma       =kind('ymax',bndbox,str(ymax[i]))
xml_=root.toprettyxml()
print(xml_)
os.chdir(save_path)                                              # save_path
save_path_file = save_path+image_name+'.xml'                            
with open(save_path_file, "w") as f: 
        f.write(xml_)  
print ('process is done')


x min : 227  |  y min :125 
x max : 330  |  y max :210 
x min : 183  |  y min :218 
x max : 296  |  y max :299 
x min : 148  |  y min :294 
x max : 281  |  y max :418 
(4, 3)
[[227 183 148]
 [125 218 294]
 [330 296 281]
 [210 299 418]]
<?xml version="1.0" ?>
<annotion>
	<path>d:/Path/rec/image/13.jpg</path>
	<filename>13</filename>
	<size>
		<width>425</width>
		<height>500</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>cutter</name>
		<pos>Unspecified</pos>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>227</xmin>
			<ymin>125</ymin>
			<xmax>330</xmax>
			<ymax>210</ymax>
		</bndbox>
	</object>
	<object>
		<name>cutter</name>
		<pos>Unspecified</pos>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>183</xmin>
			<ymin>218</ymin>
			<xmax>296</xmax>
			<ymax>299</ymax>
		</bndbox>
	</object>
	<object>
		<name>cutter</name>
		<pos>Unspecified</pos>
		<truncated>0</truncated>
		<difficult>0</difficult>

In [27]:
import numpy as np



from xml.dom import minidom, Node
def kind(object_name,roott,inside):
    '''
    obj_name is the objact to create 
    root : where to obj_name connect to
    inside is the text inside the obj_name
    '''
    obj=root.createElement(str(object_name))
    if inside:
        obj.appendChild(root.createTextNode(inside))
    roott.appendChild(obj)
    return obj
def xml_maker(name,xmin,ymin,xmax,ymax,truncated):
    root=minidom.Document()
    unn       =kind('annotion',root,None)
    folder    =kind('folder',unn,'fold')
    file_n    =kind('filename',unn,'id')
    pic_size  =kind('size',unn,None)
    pic_width =kind('width',pic_size,'w')
    pic_height=kind('height',pic_size,'s')
    dep       =kind('depth',pic_size,'3')
    seg       =kind('segmented',unn,'0')
    obj       =kind('object',unn,None)
    name      =kind('name',obj,name)
    pos       =kind('pos',obj,'Unspecified')
    truncated =kind('truncated',obj,str(truncated))
    difficult =kind('difficult',obj,'0')
    bndbox    =kind('bndbox',obj,None)
    xmi      =kind('xmin',bndbox,str(xmin))
    ymi      =kind('ymin',bndbox,str(ymin))
    xma      =kind('xmax',bndbox,str(xmax))
    yma      =kind('ymax',bndbox,str(ymax))
    xml_=root.toprettyxml()
    print(xml_)




In [26]:
from xml.dom import minidom, Node


root=minidom.Document()
ann=root.createElement('annotation')
root.appendChild(ann)


xml_str = root.toprettyxml(indent ="\t") 

print (root.toprettyxml(indent = '   '))  
from xml.dom import minidom, Node
def kind(object_name,roott,inside):
    '''
    obj_name is the objact to create 
    root : where to obj_name connect to
    inside is the text inside the obj_name
    '''
    obj=root.createElement(str(object_name))
    if inside:
        obj.appendChild(root.createTextNode(inside))
    roott.appendChild(obj)
    return obj

root=minidom.Document()
unn       =kind('annotion',root,None)
folder    =kind('folder',unn,'fold')
file_n    =kind('filename',unn,'id')
pic_size  =kind('size',unn,None)
pic_width =kind('width',pic_size,'w')
pic_height=kind('height',pic_size,'s')
dep       =kind('depth',pic_size,'3')
seg       =kind('segmented',unn,'0')
obj       =kind('object',unn,None)
name      =kind('name',obj,'cutter')
pos       =kind('pos',obj,'Unspecified')
truncated =kind('truncated',obj,'0')
difficult =kind('difficult',obj,'0')
bndbox    =kind('bndbox',obj,None)
xmi      =kind('xmin',bndbox,None)
ymi      =kind('ymin',bndbox,None)
xma      =kind('xmax',bndbox,None)
yma      =kind('ymax',bndbox,None)


xml_=root.toprettyxml()
save_num=1
save_path='d:/Path/Z+/DS1'
import os
os.chdir(save_path)
save_path_file = str('{}'.format(save_num))+'.xml'
with open(save_path_file, "w") as f: 
        f.write(xml_)  

print(xml_)

<?xml version="1.0" ?>
<annotation/>



FileNotFoundError: [WinError 3] The system cannot find the path specified: 'd:/Path/Z+/DS1'

In [4]:
root=minidom.Document()

obj=root.createElement('annotation')
root.appendChild(obj)

subobj=root.createElement('sub1')
obj.appendChild(subobj)

ss=root.createElement('subsub')
ss.appendChild(root.createTextNode('ii'))
subobj.appendChild(ss)

xml_str=root.toprettyxml()

print(xml_str)

<?xml version="1.0" ?>
<annotation>
	<sub1>
		<subsub>ii</subsub>
	</sub1>
</annotation>



In [5]:
import inspect
inspect.getsourcelines(kind)

(['def kind(object_name,roott,inside):\n',
  "    '''\n",
  '    obj_name is the objact to create \n',
  '    root : where to obj_name connect to\n',
  '    inside is the text inside the obj_name\n',
  "    '''\n",
  '    obj=root.createElement(str(object_name))\n',
  '    if inside:\n',
  '        obj.appendChild(root.createTextNode(inside))\n',
  '    roott.appendChild(obj)\n',
  '    return obj\n'],
 13)

-----
` ----- `
# IMAGES
` ----- `

In [ ]:
import os
import cv2
import random
path='d:/Path/'
os.chdir(path)
a='R'
xmin=[]
ymin=[]
xmax=[]
ymax=[]
drawing=False
def click_event(event,x,y,flags,params):
    global ix,iy,drawing,xx,yy
    if event==cv2.EVENT_LBUTTONDOWN:
        drawing = True
        #print('x min : {}  |  y min :{} '.format(x,y))
        xmin.append(x)
        ymin.append(y)
        ix,iy = x,y
        cv2.imshow('image', img)

            
            
    elif event==cv2.EVENT_LBUTTONUP:
        drawing=False
        #print('x max : {}  |  y max :{} '.format(x,y))
        
        xmax.append(x)
        ymax.append(y)
        c1,c2,c3=random.randint(0,255),random.randint(0,255),random.randint(0,200)
        cv2.rectangle(img,(ix,iy),(x,y),(c1,c2,c3),thickness=2)
        cv2.imshow('image', img)
    return xmin,ymin,xmax,ymax

if __name__=='__main__':
    img=cv2.imread('{}.jpg'.format(a))
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey()
    cv2.destroyAllWindows() 
import numpy as np
xy=np.array([xmin,ymin,xmax,ymax])
print(xy.shape)

In [ ]:
save_path='d:/Path/Z+/DS1/annotation/'
import os
os.chdir(save_path)
save_path_file = str('1')+'.xml'
with open(save_path_file, "w") as f: 
        f.write(xml_)  

